-- =============================================================================
-- Esquema de ejemplo para la integración con PostgreSQL.
--
-- Es el gemelo de docker/oracle/sql/01_schema.sql. Tablas, columnas y nombres de
-- constraint se mantienen idénticos a propósito: el mapeo de
-- src/infrastructure/repositories/entities.ts es uno solo para todos los motores,
-- así que cualquier divergencia de nombre rompería el SQL que genera el
-- repositorio genérico contra este.
--
-- SOBRE LAS MAYÚSCULAS
-- --------------------
-- El repositorio genérico emite los identificadores en MAYÚSCULAS tal cual están
-- en el mapeo (SELECT PK_USER FROM USERS). PostgreSQL, a diferencia de Oracle,
-- pliega a MINÚSCULAS todo identificador que no venga entrecomillado, y esa regla
-- se aplica igual al DDL y a las consultas. Por eso aquí se crea TODO sin
-- comillas: la tabla acaba llamándose `users` y la columna `pk_user`, y el
-- `SELECT PK_USER FROM USERS` que genera la aplicación se pliega exactamente a
-- esos mismos nombres y resuelve. Entrecomillar el DDL ("USERS") sería el único
-- modo de romperlo, porque entonces el nombre real quedaría en mayúsculas y la
-- consulta sin comillas ya no lo encontraría.
--
-- Convención que espera el repositorio:
--   - PK numérica IDENTITY    -> permite recuperar el id recién insertado
--   - AVAILABLE (0/1)         -> columna de borrado lógico (1 = vivo, 0 = borrado)
--   - CREATED_AT / UPDATED_AT -> las mantiene el repositorio genérico
--
-- Lo ejecuta sola la imagen postgres:16-alpine al inicializar el volumen, como
-- POSTGRES_USER y contra POSTGRES_DB (ver docker-compose.yml).
-- =============================================================================

-- Los DROP van en orden inverso a las FK (primero la hija, luego las padre) para
-- que el script se pueda reaplicar a mano sobre un contenedor ya inicializado
-- sin borrar el volumen.
DROP TABLE IF EXISTS AUDIT_LOG CASCADE;
DROP TABLE IF EXISTS APPOINTMENTS CASCADE;
DROP TABLE IF EXISTS BRANCHES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

-- =============================================================================
-- USERS: personas del sistema. Un usuario con IS_CLIENT = 1 puede ser el titular
-- de una cita; el resto (staff) queda disponible para futuros usos.
--
-- IS_CLIENT y AVAILABLE son SMALLINT y no BOOLEAN: el repositorio genérico enlaza
-- los flags como 1/0 numéricos para poder compartir el mapeo con Oracle, y el
-- driver no convertiría ese 1 a `true` al comparar contra una columna BOOLEAN.
-- El CHECK devuelve la garantía que BOOLEAN habría dado por sí solo.
-- =============================================================================
CREATE TABLE USERS (
  PK_USER     INT           GENERATED BY DEFAULT AS IDENTITY,
  NAME        VARCHAR(100)  NOT NULL,
  EMAIL       VARCHAR(150),
  PHONE       VARCHAR(30),
  IS_CLIENT   SMALLINT      DEFAULT 1 NOT NULL,
  AVAILABLE   SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  UPDATED_AT  TIMESTAMPTZ,
  CREATED_BY  VARCHAR(100)  DEFAULT 'System' NOT NULL,
  UPDATED_BY  VARCHAR(100),
  CONSTRAINT PK_USERS       PRIMARY KEY (PK_USER),
  CONSTRAINT CK_USERS_CLI   CHECK (IS_CLIENT IN (0, 1)),
  CONSTRAINT CK_USERS_AVAIL CHECK (AVAILABLE IN (0, 1))
);

CREATE INDEX IX_USERS_AVAILABLE ON USERS (AVAILABLE);

-- =============================================================================
-- BRANCHES: sucursales donde se agendan las citas.
--
-- OPENS_AT / CLOSES_AT siguen siendo texto 'HH:MM' y no TIME: la hora de apertura
-- es un horario de rótulo, no un instante, y así viaja al JSON sin conversiones.
-- =============================================================================
CREATE TABLE BRANCHES (
  PK_BRANCH   INT           GENERATED BY DEFAULT AS IDENTITY,
  NAME        VARCHAR(100)  NOT NULL,
  ADDRESS     VARCHAR(200),
  PHONE       VARCHAR(30),
  OPENS_AT    VARCHAR(5)    DEFAULT '09:00' NOT NULL,
  CLOSES_AT   VARCHAR(5)    DEFAULT '18:00' NOT NULL,
  AVAILABLE   SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  UPDATED_AT  TIMESTAMPTZ,
  CREATED_BY  VARCHAR(100)  DEFAULT 'System' NOT NULL,
  UPDATED_BY  VARCHAR(100),
  CONSTRAINT PK_BRANCHES       PRIMARY KEY (PK_BRANCH),
  CONSTRAINT CK_BRANCHES_AVAIL CHECK (AVAILABLE IN (0, 1))
);

CREATE INDEX IX_BRANCHES_AVAILABLE ON BRANCHES (AVAILABLE);

-- =============================================================================
-- APPOINTMENTS: la cita. Puede ser de un cliente registrado (FK_CLIENT) o de
-- alguien que llega sin registro, en cuyo caso sólo guardamos GUEST_NAME.
-- CK_APPT_PARTY garantiza que siempre haya al menos uno de los dos, de modo que
-- ninguna cita quede sin titular identificable.
-- =============================================================================
CREATE TABLE APPOINTMENTS (
  PK_APPOINTMENT INT           GENERATED BY DEFAULT AS IDENTITY,
  FK_BRANCH      INT           NOT NULL,
  FK_CLIENT      INT,
  GUEST_NAME     VARCHAR(100),
  SCHEDULED_AT   TIMESTAMPTZ   NOT NULL,
  DURATION_MIN   INT           DEFAULT 30 NOT NULL,
  STATUS         VARCHAR(20)   DEFAULT 'PENDING' NOT NULL,
  DETAILS        VARCHAR(500),
  AVAILABLE      SMALLINT      DEFAULT 1 NOT NULL,
  CREATED_AT     TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  UPDATED_AT     TIMESTAMPTZ,
  CREATED_BY     VARCHAR(100)  DEFAULT 'System' NOT NULL,
  UPDATED_BY     VARCHAR(100),
  CONSTRAINT PK_APPOINTMENTS  PRIMARY KEY (PK_APPOINTMENT),
  CONSTRAINT FK_APPT_BRANCH   FOREIGN KEY (FK_BRANCH) REFERENCES BRANCHES (PK_BRANCH),
  CONSTRAINT FK_APPT_CLIENT   FOREIGN KEY (FK_CLIENT) REFERENCES USERS (PK_USER),
  CONSTRAINT CK_APPT_STATUS   CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'DONE', 'CANCELLED')),
  CONSTRAINT CK_APPT_DURATION CHECK (DURATION_MIN BETWEEN 5 AND 1440),
  CONSTRAINT CK_APPT_AVAIL    CHECK (AVAILABLE IN (0, 1)),
  CONSTRAINT CK_APPT_PARTY    CHECK (FK_CLIENT IS NOT NULL OR GUEST_NAME IS NOT NULL)
);

CREATE INDEX IX_APPT_BRANCH    ON APPOINTMENTS (FK_BRANCH);
CREATE INDEX IX_APPT_CLIENT    ON APPOINTMENTS (FK_CLIENT);
CREATE INDEX IX_APPT_SCHEDULED ON APPOINTMENTS (SCHEDULED_AT);
CREATE INDEX IX_APPT_AVAILABLE ON APPOINTMENTS (AVAILABLE);

-- =============================================================================
-- AUDIT_LOG: bitacora de cambios. La escribe el repositorio generico despues de
-- cada escritura, dentro de la misma transaccion que la operacion auditada.
-- No tiene borrado logico a proposito: una linea de auditoria no se borra.
--
-- CHANGES es TEXT (equivalente al CLOB de Oracle y al NVARCHAR(MAX) de T-SQL):
-- guarda el diff serializado, cuyo tamaño no tiene tope razonable.
-- =============================================================================
CREATE TABLE AUDIT_LOG (
  PK_AUDIT    INT           GENERATED BY DEFAULT AS IDENTITY,
  ENTITY      VARCHAR(50)   NOT NULL,
  ENTITY_ID   VARCHAR(50),
  ACTION      VARCHAR(20)   NOT NULL,
  CHANGED_BY  VARCHAR(100)  DEFAULT 'System' NOT NULL,
  CHANGED_AT  TIMESTAMPTZ   DEFAULT NOW() NOT NULL,
  REQUEST_ID  VARCHAR(64),
  CHANGES     TEXT,
  CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (PK_AUDIT)
);

CREATE INDEX IX_AUDIT_ENTITY  ON AUDIT_LOG (ENTITY, ENTITY_ID);
CREATE INDEX IX_AUDIT_REQUEST ON AUDIT_LOG (REQUEST_ID);
