-- =============================================================================
-- Esquema de ejemplo para la integración con Oracle.
--
-- Tres tablas que comparten la misma convención, que es la que el repositorio
-- genérico (OracleGenericRepository) espera por defecto:
--   - PK numérica IDENTITY  -> permite INSERT ... RETURNING <pk> INTO :out_pk
--   - AVAILABLE NUMBER(1)   -> columna de borrado lógico (1 = vivo, 0 = borrado)
--   - CREATED_AT / UPDATED_AT TIMESTAMP -> las mantiene el repositorio genérico
--
-- Se ejecuta como APP_USER dentro del PDB (ver docker/oracle/init/00_init.sh).
-- =============================================================================

-- Los DROP son tolerantes para que el script se pueda reaplicar a mano sobre un
-- contenedor ya inicializado sin tener que borrar el volumen.
BEGIN
  FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('AUDIT_LOG', 'APPOINTMENTS', 'BRANCHES', 'USERS')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- =============================================================================
-- USERS: personas del sistema. Un usuario con IS_CLIENT = 1 puede ser el titular
-- de una cita; el resto (staff) queda disponible para futuros usos.
-- =============================================================================
CREATE TABLE USERS (
  PK_USER     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NAME        VARCHAR2(100)  NOT NULL,
  EMAIL       VARCHAR2(150),
  PHONE       VARCHAR2(30),
  WALLET      NUMBER(10, 2),
  IS_CLIENT   NUMBER(1)      DEFAULT 1 NOT NULL,
  AVAILABLE   NUMBER(1)      DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP,
  CREATED_BY  VARCHAR2(100)  DEFAULT 'System' NOT NULL,
  UPDATED_BY  VARCHAR2(100),
  CONSTRAINT PK_USERS       PRIMARY KEY (PK_USER),
  CONSTRAINT CK_USERS_CLI   CHECK (IS_CLIENT IN (0, 1)),
  CONSTRAINT CK_USERS_AVAIL CHECK (AVAILABLE IN (0, 1))
);

CREATE INDEX IX_USERS_AVAILABLE ON USERS (AVAILABLE);

-- =============================================================================
-- BRANCHES: sucursales donde se agendan las citas.
-- =============================================================================
CREATE TABLE BRANCHES (
  PK_BRANCH   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  NAME        VARCHAR2(100)  NOT NULL,
  ADDRESS     VARCHAR2(200),
  PHONE       VARCHAR2(30),
  OPENS_AT    VARCHAR2(5)    DEFAULT '09:00' NOT NULL,
  CLOSES_AT   VARCHAR2(5)    DEFAULT '18:00' NOT NULL,
  AVAILABLE   NUMBER(1)      DEFAULT 1 NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP,
  CREATED_BY  VARCHAR2(100)  DEFAULT 'System' NOT NULL,
  UPDATED_BY  VARCHAR2(100),
  CONSTRAINT PK_BRANCHES       PRIMARY KEY (PK_BRANCH),
  CONSTRAINT CK_BRANCHES_AVAIL CHECK (AVAILABLE IN (0, 1))
);

CREATE INDEX IX_BRANCHES_AVAILABLE ON BRANCHES (AVAILABLE);

-- =============================================================================
-- APPOINTMENTS: la cita. Puede ser de un cliente registrado (FK_CLIENT) o de
-- alguien que llega sin registro, en cuyo caso sólo guardamos GUEST_NAME.
-- CK_APPT_PARTY garantiza que siempre haya al menos uno de los dos, de modo que
-- ninguna cita quede sin titular identificable.
-- =============================================================================
CREATE TABLE APPOINTMENTS (
  PK_APPOINTMENT NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  FK_BRANCH      NUMBER         NOT NULL,
  FK_CLIENT      NUMBER,
  GUEST_NAME     VARCHAR2(100),
  SCHEDULED_AT   TIMESTAMP      NOT NULL,
  DURATION_MIN   NUMBER(4)      DEFAULT 30 NOT NULL,
  STATUS         VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
  DETAILS        VARCHAR2(500),
  AVAILABLE      NUMBER(1)      DEFAULT 1 NOT NULL,
  CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP,
  CREATED_BY     VARCHAR2(100)  DEFAULT 'System' NOT NULL,
  UPDATED_BY     VARCHAR2(100),
  CONSTRAINT PK_APPOINTMENTS  PRIMARY KEY (PK_APPOINTMENT),
  CONSTRAINT FK_APPT_BRANCH   FOREIGN KEY (FK_BRANCH) REFERENCES BRANCHES (PK_BRANCH),
  CONSTRAINT FK_APPT_CLIENT   FOREIGN KEY (FK_CLIENT) REFERENCES USERS (PK_USER),
  CONSTRAINT CK_APPT_STATUS   CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'DONE', 'CANCELLED')),
  CONSTRAINT CK_APPT_DURATION CHECK (DURATION_MIN BETWEEN 5 AND 1440),
  CONSTRAINT CK_APPT_AVAIL    CHECK (AVAILABLE IN (0, 1)),
  CONSTRAINT CK_APPT_PARTY    CHECK (FK_CLIENT IS NOT NULL OR GUEST_NAME IS NOT NULL)
);

CREATE INDEX IX_APPT_BRANCH    ON APPOINTMENTS (FK_BRANCH);
CREATE INDEX IX_APPT_CLIENT    ON APPOINTMENTS (FK_CLIENT);
CREATE INDEX IX_APPT_SCHEDULED ON APPOINTMENTS (SCHEDULED_AT);
CREATE INDEX IX_APPT_AVAILABLE ON APPOINTMENTS (AVAILABLE);

-- Ultima red contra la doble reserva.
--
-- La aplicacion ya serializa el alta bloqueando la sucursal (SELECT ... FOR
-- UPDATE), pero ese bloqueo solo alcanza a las peticiones del mismo proceso:
-- con dos instancias corriendo, la garantia tiene que estar aqui.
--
-- Cubre el mismo inicio exacto, no el solape parcial.
--
-- Oracle no tiene indices parciales, asi que se emula con uno basado en
-- funcion: las filas que no deben participar producen (NULL, NULL), y una
-- entrada enteramente nula no se indexa, con lo que no compite por la unicidad.
-- Es la forma canonica de escribir "unico solo cuando se cumple X" en Oracle.
CREATE UNIQUE INDEX UX_APPT_SLOT ON APPOINTMENTS (
  CASE WHEN AVAILABLE = 1 AND STATUS <> 'CANCELLED' THEN FK_BRANCH    END,
  CASE WHEN AVAILABLE = 1 AND STATUS <> 'CANCELLED' THEN SCHEDULED_AT END
);

-- =============================================================================
-- AUDIT_LOG: bitacora de cambios. La escribe el repositorio generico despues de
-- cada escritura, dentro de la misma transaccion que la operacion auditada.
-- No tiene borrado logico a proposito: una linea de auditoria no se borra.
-- =============================================================================
CREATE TABLE AUDIT_LOG (
  PK_AUDIT    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ENTITY      VARCHAR2(50)   NOT NULL,
  ENTITY_ID   VARCHAR2(50),
  ACTION      VARCHAR2(20)   NOT NULL,
  CHANGED_BY  VARCHAR2(100)  DEFAULT 'System' NOT NULL,
  CHANGED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  REQUEST_ID  VARCHAR2(64),
  CHANGES     VARCHAR2(4000),
  CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (PK_AUDIT)
);

CREATE INDEX IX_AUDIT_ENTITY  ON AUDIT_LOG (ENTITY, ENTITY_ID);
CREATE INDEX IX_AUDIT_REQUEST ON AUDIT_LOG (REQUEST_ID);

COMMIT;
