// src/core/config/swagger.config.ts
import { container } from "tsyringe";
import { IEnvs } from "../../domain/interfaces/infrastructure/plugins/envs.plugin.interface";
import { Options } from "swagger-jsdoc";

export const getSwaggerOptions = (): Options => {
  const envs: IEnvs = container.resolve("IEnvs");

  return {
    definition: {
      openapi: "3.0.0",
      info: {
        title: "Test API",
        version: "1.0.0",
        description: "Test Express API with autogenerated swagger doc",
      },
      servers: [
        {
          url: `http://localhost:${envs.getEnv("PORT") || 3000}`,
          description: "Local server",
        },
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            description:
              'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"',
            type: "http",
            scheme: "bearer",
            bearerFormat: "JWT",
          },
        },
      },
      security: [{ bearerAuth: [] }],
    },
    apis: ["./src/presentation/routes/*.ts", "./src/application/dtos/*.ts"],
  };
};
