import { Options } from "swagger-jsdoc";

const routesPath ="./src/presentation/routes/*.ts";
      const dtosPath = "./src/application/dtos/*.ts";
      export const swaggerOptions: Options = {
      
      definition: {
          
          openapi: "3.0.0",
          info: {
            title: "Test API",
            version: "1.0.0",
            description: "Test Express API with autogenerated swagger doc",
            // contact: {
            //   name: 'API Support',
            //   url: 'http://www.example.com/support',
            //   email: 'support@example.com',
            // },
            // termsOfService: 'http://example.com/terms/',
            // license: {
            //   name: 'Apache 2.0',
            //   url: 'https://www.apache.org/licenses/LICENSE-2.0.html',
            // },

          },
         
          servers:[
            { url: "http://localhost:3001", description: "Local server" }
            
          ],
          components: {

            securitySchemes: {
              bearerAuth: {
                description: "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                type: "http",
                scheme: "bearer",
                bearerFormat: "JWT",
              },
            },
          },
          security: [
            {
              bearerAuth: [
              
              ],

            },
          ],  
        },
        apis: [routesPath, dtosPath],
        


      };