import { Options } from 'swagger-jsdoc';

const routesPath ='./src/presentation/routes/*.ts';
      const dtosPath = './src/application/dtos/*.ts';
      export const swaggerOptions: Options = {

      definition: {

          openapi: '3.0.0',
          info: {
            title: 'Test API',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc',
          },
          host: 'localhost:3000',
          components: {
            securitySchemes: {
              bearerAuth: {
                type: 'http',
                scheme: 'bearer',
                bearerFormat: 'JWT',
              },
            },
          },
          security: [{ bearerAuth: [] }],
        },
        apis: [routesPath, dtosPath],

      };